### ISSUE TITLE
Scalecodec sometimes doesn't seem to recognize xx chain properties

### ISSUE THREAD

**Issue by armchairancap** [xx-labs/xxchain#7]
I saw this when running an xx script.

```python
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/scalecodec/types.py", line 1232, in process
    enum_type_mapping = self.type_mapping[self.index]
IndexError: list index out of range
```

Scalecodec version: `scalecodec-1.2.7`

Scalecodec error:

```python
  File "/home/user/.local/lib/python3.9/site-packages/scalecodec/types.py", line 1245, in process
    raise ValueError("Index '{}' not present in Enum type mapping".format(self.index))
ValueError: Index '109' not present in Enum type mapping

```

I just upgraded to scalecodec-1.2.9, but haven't had a chance to try and the problem didn't regularly appeared in the first place - this is the first time I saw this problem so even if 1.2.9 fixes it, it will take months to know for sure.

I think the reason may be we'd need to make scalecodec aware of our blockchain. Current list of chains recognized by scalecodec:
https://github.com/polkadot-js/api/tree/master/packages/types-known/src/spec

Template for submission:
https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/substrate-node-template.json

Example PR for other Substate-based chains: 
https://github.com/polkascan/py-scale-codec/pull/50/files

**Comment by armchairancap** [comment]
Not sure if setting remote preset to `False` fixes it, but I haven't observed errors since I changed from`True`.
